### PR TITLE
added GetEC() and CryptoKey(EC.Key ec) to CryptoKey

### PR DESCRIPTION
**Pull request by ffleischer**
I think this was just missing or is there a special reason why it was not implemented?

### CODE REVIEW

**Comment by flaub** [comment]
Would you mind converting spaces to tabs; for consistency.

**Comment by ffleischer** [comment]
Sorry, my bad.

**Comment by flaub** [comment]
@adamcaudill Mind if I merge this?

**Comment by adamcaudill** [comment]
@flaub Be my guest - I had intended to merge it this evening.

**Pull request merged**
